CREATE TABLE customers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(100)                            NOT NULL,
    email           VARCHAR(100),
    phone           VARCHAR(20),
    address         TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);
-- customer_number VARCHAR(12) GENERATED BY DEFAULT AS INSERT NOT NULL,

CREATE TABLE machine_telemetry
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    machine_id        VARCHAR(255),
    status            VARCHAR(255),
    current_operation VARCHAR(255),
    error_code        VARCHAR(255),
    CONSTRAINT pk_machine_telemetry PRIMARY KEY (id)
);



CREATE TABLE service_orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id      BIGINT,
    source           VARCHAR(255),
    status           VARCHAR(255),
    priority         VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    due_date         date,
    notes            VARCHAR(255),
    shoptet_id       VARCHAR(255),
    pohoda_id        VARCHAR(255),
    external_api_id  VARCHAR(255),
    order_number     VARCHAR(255),
    date_created     date,
    date_from        date,
    date_to          date,
    customer_company VARCHAR(255),
    customer_name    VARCHAR(255),
    customer_city    VARCHAR(255),
    customer_street  VARCHAR(255),
    customer_zip     VARCHAR(255),
    customer_ico     VARCHAR(255),
    customer_email   VARCHAR(255),
    customer_phone   VARCHAR(255),
    note             VARCHAR(255),
    internal_note    VARCHAR(255),
    total_price      DECIMAL,
    order_code       VARCHAR(255),
    date             TIMESTAMP WITHOUT TIME ZONE,
    is_paid          VARCHAR(255),
    CONSTRAINT pk_service_orders PRIMARY KEY (id)
);

CREATE TABLE skis
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ski_number        VARCHAR(12)                             ,
    brand             VARCHAR(50)                             NOT NULL,
    model             VARCHAR(100)                            NOT NULL,
    length            VARCHAR(10)                             NOT NULL,
    year              INTEGER,
    ski_type          VARCHAR(50),
    weight_kg         DECIMAL(5, 2),
    condition         SKI_CONDITION,
    status            SKI_STATUS,
    location          VARCHAR(100),
    notes             TEXT,
    last_service_date date,
    next_service_date date,
    struktura         VARCHAR(100),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_skis PRIMARY KEY (id)
);

/*ALTER TABLE customers
    ADD CONSTRAINT uc_customers_customer_number UNIQUE (customer_number);*/

/*ALTER TABLE skis
    ADD CONSTRAINT uc_skis_ski_number UNIQUE (ski_number);*/



ALTER TABLE service_orders
    ADD CONSTRAINT FK_SERVICE_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);