CREATE TABLE order_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id         BIGINT,
    ski_id           BIGINT,
    task_name        VARCHAR(255),
    task_instruction VARCHAR(255),
    price            DECIMAL,
    product_text     VARCHAR(255),
    product_code     VARCHAR(255),
    quantity         DECIMAL,
    unit_price       DECIMAL,
    unit             VARCHAR(255),
    name             VARCHAR(255),
    amount           INTEGER,
    remark           VARCHAR(255),
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES service_orders (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_SKI FOREIGN KEY (ski_id) REFERENCES skis (id);