spring:
  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET:DZJGZJGjzgfgzt736R36frehuhuGEUGUFEGHU38437RGFZUJRGHEUHEFIEZ888888888888888888888EDGUFHVGERHGehfghgrehfgbrehgfeurhigfrei}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.ski.inventory: INFO
    org.springframework.security: WARN
