services:
  # Databáze
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_ski_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ski_connection
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ski_connection"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend
  connection-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: connection_backend
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ski_connection
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=dev-secret-key-minimum-32-characters-long-for-testing
      - SERVER_PORT=8080
      - SHOW_SQL=true
      - SPRING_FLYWAY_TABLE=flyway_schema_history_connection
      - SPRING_FLYWAY_ENABLED=true
      - api.bezky-servis.url=https://bezkyservis.xyz
      - api.machine.url=http://localhost:5000
    ports:
      - "8081:8080"
    networks:
      - shared-net

networks:
  shared-net:

volumes:
  postgres_data:

#services:
#
#
#  #Backend
#  connection-service:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    container_name: connection_backend
##    depends_on:
##      db-postgres:
##        condition: service_healthy # Čeká, až bude DB připravená
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_NAME=ski_inventory
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - JWT_SECRET=dev-secret-key-minimum-32-characters-long-for-testing
#      - SERVER_PORT=8080
#      - SHOW_SQL=true
#      - SPRING_FLYWAY_TABLE=flyway_schema_history_connection
#      - SPRING_FLYWAY_ENABLED=false
#    ports:
#      - "8081:8080"
#
#    networks:
#      - shared-net
#
#
#networks:
#  shared-net:
#    external: true
##  postgres:
##    image: postgres:16-alpine
##    container_name: postgres-ski-connection
##    restart: unless-stopped
##    environment:
##      - POSTGRES_DB=ski_conection
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=postgres
##    ports:
##      - "5432:5432"
##    healthcheck:
##      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
##      interval: 10s
##      timeout: 5s
##      retries: 5
