name: Secure Docker Deploy

on:
  #push:
    #branches: [ main ] # Spustí se jen při pushi do main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USERNAME }}/app"

      - name: Blue-green deploy (bez výpadku)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/app
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
            echo "NEXT_PUBLIC_API_URL=" >> .env
            echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
            mkdir -p docker/ssl
            echo "${{ secrets.SSL_PRIVATE_KEY_B64 }}" | base64 -d > docker/ssl/key.pem
            chmod 600 docker/ssl/key.pem
            sudo bash docker/scripts/blue-green-deploy.sh
